spring:
    datasource:
        url: jdbc:postgresql://localhost:5433/bankAppDB
        username: postgres
        password: postgres
    jpa:
      generate-ddl: true
    hibernate:
            generateDdl: false

hibernate:
  hbm2ddl:
    auto: create-drop

server:
  port: 8081